linters-settings:
  gofmt:
    simplify: true
    tabs: true
    tab-width: 8

linters:
  enable:
    - gofmt
    - whitespace

issues:
  exclude-use-default: false
  exclude-rules:
    - path: _test\.go
      linters:
        - gofmt
        - whitespace

run:
  tests: true
