---
grpc_server:
  addr: :8080
datastore:
  path: data
p2p:
  multiaddr: "/ip4/0.0.0.0/tcp/0"
  conn_limit: [100, 400]
log:
  dev: true
  out_paths:
    - stdout
    # for an example, logs can be also written to a filepath
    #- out.log
  err_paths:
    - stderr
