// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0-devel
// 	protoc        v4.24.3
// source: internal/swn/pb/auth_model.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type KeyType int32

const (
	KeyType_RSA       KeyType = 0
	KeyType_Ed25519   KeyType = 1
	KeyType_Secp256k1 KeyType = 2
	KeyType_ECDSA     KeyType = 3
)

// Enum value maps for KeyType.
var (
	KeyType_name = map[int32]string{
		0: "RSA",
		1: "Ed25519",
		2: "Secp256k1",
		3: "ECDSA",
	}
	KeyType_value = map[string]int32{
		"RSA":       0,
		"Ed25519":   1,
		"Secp256k1": 2,
		"ECDSA":     3,
	}
)

func (x KeyType) Enum() *KeyType {
	p := new(KeyType)
	*p = x
	return p
}

func (x KeyType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (KeyType) Descriptor() protoreflect.EnumDescriptor {
	return file_internal_swn_pb_auth_model_proto_enumTypes[0].Descriptor()
}

func (KeyType) Type() protoreflect.EnumType {
	return &file_internal_swn_pb_auth_model_proto_enumTypes[0]
}

func (x KeyType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use KeyType.Descriptor instead.
func (KeyType) EnumDescriptor() ([]byte, []int) {
	return file_internal_swn_pb_auth_model_proto_rawDescGZIP(), []int{0}
}

type DeviceId struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DeviceId []byte `protobuf:"bytes,1,opt,name=Device_id,json=DeviceId,proto3" json:"Device_id,omitempty"`
}

func (x *DeviceId) Reset() {
	*x = DeviceId{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_swn_pb_auth_model_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeviceId) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeviceId) ProtoMessage() {}

func (x *DeviceId) ProtoReflect() protoreflect.Message {
	mi := &file_internal_swn_pb_auth_model_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeviceId.ProtoReflect.Descriptor instead.
func (*DeviceId) Descriptor() ([]byte, []int) {
	return file_internal_swn_pb_auth_model_proto_rawDescGZIP(), []int{0}
}

func (x *DeviceId) GetDeviceId() []byte {
	if x != nil {
		return x.DeviceId
	}
	return nil
}

type AccID struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AccId []byte `protobuf:"bytes,1,opt,name=Acc_id,json=AccId,proto3" json:"Acc_id,omitempty"`
}

func (x *AccID) Reset() {
	*x = AccID{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_swn_pb_auth_model_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AccID) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccID) ProtoMessage() {}

func (x *AccID) ProtoReflect() protoreflect.Message {
	mi := &file_internal_swn_pb_auth_model_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccID.ProtoReflect.Descriptor instead.
func (*AccID) Descriptor() ([]byte, []int) {
	return file_internal_swn_pb_auth_model_proto_rawDescGZIP(), []int{1}
}

func (x *AccID) GetAccId() []byte {
	if x != nil {
		return x.AccId
	}
	return nil
}

type PeerId struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data []byte `protobuf:"bytes,1,opt,name=Data,proto3" json:"Data,omitempty"`
}

func (x *PeerId) Reset() {
	*x = PeerId{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_swn_pb_auth_model_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PeerId) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PeerId) ProtoMessage() {}

func (x *PeerId) ProtoReflect() protoreflect.Message {
	mi := &file_internal_swn_pb_auth_model_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PeerId.ProtoReflect.Descriptor instead.
func (*PeerId) Descriptor() ([]byte, []int) {
	return file_internal_swn_pb_auth_model_proto_rawDescGZIP(), []int{2}
}

func (x *PeerId) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type AuthInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OtherDevicePubKey  []byte `protobuf:"bytes,1,opt,name=OtherDevicePubKey,proto3" json:"OtherDevicePubKey,omitempty"`
	MyDevicePrivateKey []byte `protobuf:"bytes,2,opt,name=MyDevicePrivateKey,proto3" json:"MyDevicePrivateKey,omitempty"`
}

func (x *AuthInfo) Reset() {
	*x = AuthInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_swn_pb_auth_model_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AuthInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthInfo) ProtoMessage() {}

func (x *AuthInfo) ProtoReflect() protoreflect.Message {
	mi := &file_internal_swn_pb_auth_model_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthInfo.ProtoReflect.Descriptor instead.
func (*AuthInfo) Descriptor() ([]byte, []int) {
	return file_internal_swn_pb_auth_model_proto_rawDescGZIP(), []int{3}
}

func (x *AuthInfo) GetOtherDevicePubKey() []byte {
	if x != nil {
		return x.OtherDevicePubKey
	}
	return nil
}

func (x *AuthInfo) GetMyDevicePrivateKey() []byte {
	if x != nil {
		return x.MyDevicePrivateKey
	}
	return nil
}

var File_internal_swn_pb_auth_model_proto protoreflect.FileDescriptor

var file_internal_swn_pb_auth_model_proto_rawDesc = []byte{
	0x0a, 0x20, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x73, 0x77, 0x6e, 0x2f, 0x70,
	0x62, 0x2f, 0x61, 0x75, 0x74, 0x68, 0x5f, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x0d, 0x61, 0x75, 0x74, 0x68, 0x5f, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2e, 0x70,
	0x62, 0x22, 0x27, 0x0a, 0x08, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x49, 0x64, 0x12, 0x1b, 0x0a,
	0x09, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c,
	0x52, 0x08, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x49, 0x64, 0x22, 0x1e, 0x0a, 0x05, 0x41, 0x63,
	0x63, 0x49, 0x44, 0x12, 0x15, 0x0a, 0x06, 0x41, 0x63, 0x63, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0c, 0x52, 0x05, 0x41, 0x63, 0x63, 0x49, 0x64, 0x22, 0x1c, 0x0a, 0x06, 0x50, 0x65,
	0x65, 0x72, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x44, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0c, 0x52, 0x04, 0x44, 0x61, 0x74, 0x61, 0x22, 0x68, 0x0a, 0x08, 0x41, 0x75, 0x74, 0x68,
	0x49, 0x6e, 0x66, 0x6f, 0x12, 0x2c, 0x0a, 0x11, 0x4f, 0x74, 0x68, 0x65, 0x72, 0x44, 0x65, 0x76,
	0x69, 0x63, 0x65, 0x50, 0x75, 0x62, 0x4b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52,
	0x11, 0x4f, 0x74, 0x68, 0x65, 0x72, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x50, 0x75, 0x62, 0x4b,
	0x65, 0x79, 0x12, 0x2e, 0x0a, 0x12, 0x4d, 0x79, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x50, 0x72,
	0x69, 0x76, 0x61, 0x74, 0x65, 0x4b, 0x65, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x12,
	0x4d, 0x79, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x50, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x4b,
	0x65, 0x79, 0x2a, 0x39, 0x0a, 0x07, 0x4b, 0x65, 0x79, 0x54, 0x79, 0x70, 0x65, 0x12, 0x07, 0x0a,
	0x03, 0x52, 0x53, 0x41, 0x10, 0x00, 0x12, 0x0b, 0x0a, 0x07, 0x45, 0x64, 0x32, 0x35, 0x35, 0x31,
	0x39, 0x10, 0x01, 0x12, 0x0d, 0x0a, 0x09, 0x53, 0x65, 0x63, 0x70, 0x32, 0x35, 0x36, 0x6b, 0x31,
	0x10, 0x02, 0x12, 0x09, 0x0a, 0x05, 0x45, 0x43, 0x44, 0x53, 0x41, 0x10, 0x03, 0x42, 0x25, 0x5a,
	0x23, 0x67, 0x6f, 0x2e, 0x6e, 0x65, 0x6f, 0x6e, 0x79, 0x78, 0x2e, 0x69, 0x6f, 0x2f, 0x67, 0x6f,
	0x2d, 0x73, 0x77, 0x6e, 0x2f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x73, 0x77,
	0x6e, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_internal_swn_pb_auth_model_proto_rawDescOnce sync.Once
	file_internal_swn_pb_auth_model_proto_rawDescData = file_internal_swn_pb_auth_model_proto_rawDesc
)

func file_internal_swn_pb_auth_model_proto_rawDescGZIP() []byte {
	file_internal_swn_pb_auth_model_proto_rawDescOnce.Do(func() {
		file_internal_swn_pb_auth_model_proto_rawDescData = protoimpl.X.CompressGZIP(file_internal_swn_pb_auth_model_proto_rawDescData)
	})
	return file_internal_swn_pb_auth_model_proto_rawDescData
}

var file_internal_swn_pb_auth_model_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_internal_swn_pb_auth_model_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_internal_swn_pb_auth_model_proto_goTypes = []interface{}{
	(KeyType)(0),     // 0: auth_model.pb.KeyType
	(*DeviceId)(nil), // 1: auth_model.pb.DeviceId
	(*AccID)(nil),    // 2: auth_model.pb.AccID
	(*PeerId)(nil),   // 3: auth_model.pb.PeerId
	(*AuthInfo)(nil), // 4: auth_model.pb.AuthInfo
}
var file_internal_swn_pb_auth_model_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_internal_swn_pb_auth_model_proto_init() }
func file_internal_swn_pb_auth_model_proto_init() {
	if File_internal_swn_pb_auth_model_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_internal_swn_pb_auth_model_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeviceId); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_swn_pb_auth_model_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AccID); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_swn_pb_auth_model_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PeerId); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_swn_pb_auth_model_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AuthInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_internal_swn_pb_auth_model_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_internal_swn_pb_auth_model_proto_goTypes,
		DependencyIndexes: file_internal_swn_pb_auth_model_proto_depIdxs,
		EnumInfos:         file_internal_swn_pb_auth_model_proto_enumTypes,
		MessageInfos:      file_internal_swn_pb_auth_model_proto_msgTypes,
	}.Build()
	File_internal_swn_pb_auth_model_proto = out.File
	file_internal_swn_pb_auth_model_proto_rawDesc = nil
	file_internal_swn_pb_auth_model_proto_goTypes = nil
	file_internal_swn_pb_auth_model_proto_depIdxs = nil
}
